import { StyleSheet, Text, StyleProp, TextStyle , View, ScrollView } from 'react-native';
import React from 'react';
import { responsiveScreenHeight, responsiveScreenWidth } from 'react-native-responsive-dimensions';
import { Roboto } from '../../utils/commons/Fonts';
import color from '../../utils/commons/ColorsCommon';

type PropsTermsConditionComponentType = {
  backgroundColor : string,
  styleParagraphe : StyleProp<TextStyle>,
  styleTitle      : StyleProp<TextStyle>
}


const TermsConditionsComponent = ({backgroundColor, styleParagraphe, styleTitle} : PropsTermsConditionComponentType) => {

  const terms = [
    { title: 'A. CONDICIONES GENERALES.' },
    { paragraphe: 'Los presentes términos y condiciones (“Términos y Condiciones”) serán aplicables a todos los Usuarios que hagan uso de la plataforma digital e informática (“Plataforma”) a través de la aplicación móvil para teléfonos inteligentes y/o cualquier otro dispositivo o medio electrónico (“Aplicación”) cuya titularidad corresponde a, o está controlado por Propimex, S. de R.L. de C.V. ( “Nutenta”) y cualesquier portales, desarrollos y/o programas adicionales o auxiliares que, directa o indirectamente, utilice Nutenta para prestar sus servicios (conjuntamente, “Medios Digitales”). En el presente instrumento, Nutenta podrá ser referida, indistintamente, como “nosotros”, asimismo, las frases “nuestro” o “de nosotros” se entenderán referidas a Nutenta. Los Términos y Condiciones también podrán ser referidos, indistintamente, como el “presente documento” o el “presente instrumento”.' },
    { paragraphe: 'Los presentes Términos y Condiciones se encuentran dirigidos a los Usuarios de la Plataforma, y les resultan aplicables y vinculantes en todo momento que tengan la calidad de Usuarios y se encuentran dirigidos exclusivamente a los usuarios que se encuentren en el territorio de los Estados Unidos Mexicanos (“México”). Serán referidos como “Usuarios” todas las personas físicas o morales, o representantes en cualquier forma de los mismos a quienes Nutenta les proporcione un usuario y contraseña para acceder y/o utilizar o bien se registren y posteriormente, accedan y utilicen la Plataforma, por cualquier dispositivo tecnológico u ordenador, sin importar que dicho acceso se realice por conducto de la Aplicación o el Sitio Web. En particular, se identificará como Usuarios a aquellas personas que realicen una Transacción. Los presentes Términos y Condiciones están destinados y dirigidos a regular las condiciones de registro, afiliación, acceso, uso y aprovechamiento de los Medios Digitales, así como las previsiones aplicables a las Transacciones que celebren los Usuarios con Nutenta (en conjunto, los “Servicios”).' },
    { paragraphe: 'Este documento contiene información legal que le recomendamos leer completamente en conjunto con el aviso de privacidad de Nutenta que se encuentra a su disposición en la sección de “Mi Perfil” de la Aplicación (“Aviso de Privacidad”). Por medio de la aprobación de los presentes Términos y Condiciones a través de la Plataforma, se entiende que el Usuario los ha leído y aceptado, en todas sus partes, y entiende que éstos le son legalmente vinculantes y obligatorios. Por tanto, acepta las condiciones de utilización y aprovechamiento de la Plataforma, la Aplicación y los Servicios. En caso contrario, el Usuario deberá abstenerse de acceder a la Plataforma, la Aplicación y/o los Servicios, ya sea directa o indirectamente, y de utilizar cualquier información o servicio provisto por la misma, en cuyo caso, Nutenta quedará liberado de cualquier responsabilidad derivado del uso de la Plataforma y/o la Aplicación por parte del Usuario que no haya aceptado estos Términos y Condiciones. Si Usted no está de acuerdo con estos términos y condiciones, le rogamos no utilizar los Medios Digitales aquí señalados.' },
    { title: 'ACEPTACIÓN DE LOS TÉRMINOS Y CONDICIONES.' },
    { paragraphe: 'De forma previa al uso de los Medios Digitales, los presentes Términos y Condiciones serán desplegados frente al Usuario para su aceptación expresa, misma que se realizará por medios electrónicos y mediante el llenado y/o el marcado de casillas, opciones o botones de aceptación expresamente habilitados en los Medios Digitales para tal efecto, lo anterior con fundamento en la segunda fracción del Artículo 1803 del Código Civil Federal y sus correlativos y aplicables de los Códigos Civiles de las Entidades Federativas de la República Mexicana.' },
    { paragraphe: 'Los Usuarios declaran y garantizan que, previamente al uso directo o indirecto de cualquiera de los Medios Digitales, así como la realización de cualquier Transacción a través de los mismos, han aceptado expresamente todas y cada una de las disposiciones contenidas y previstas en los presentes Términos y Condiciones, así como la sujeción correspondiente a los mismos y a todas las demás reglas de operación, políticas y procedimientos que puedan ser publicados por Nutenta en la Plataforma y/o la Aplicación, cada uno de los cuales se incorpora por referencia, en términos del párrafo que antecede. En caso de que Nutenta no tenga constancia de la previa aceptación de algún Usuario de lo previsto en el presente instrumento, no se habilitarán los Servicios.' },
    { paragraphe: 'Para el supuesto de que los Usuarios por cualquier motivo no deseen obligarse con los Términos y Condiciones, o de no estar conformes con la totalidad o una parte de las previsiones aquí contenidas, deberán abstenerse de utilizar los Medios Digitales y en su caso, de utilizar los Servicios o de celebrar alguna Transacción, además de abandonar inmediatamente cualquier Medio Digital que se encuentren utilizando o que hayan utilizado o donde se hayan registrado. Nutenta garantizará el derecho de los Usuarios de revocar su consentimiento respecto de la aceptación del presente instrumento, en cuyo caso bastará con que el propio Usuario lo comunique al Centro de Atención y Soporte (como dicho término se define adelante) de Nutenta. No obstante, si por alguna razón el Usuario hiciera uso de los Servicios sin haber aceptado previamente los Términos y Condiciones, Nutenta quedará liberada de cualquier responsabilidad frente a dicho Usuario.' },
    { paragraphe: 'Sin perjuicio de lo anterior, algunos servicios que se ofrecen en la Aplicación pueden estar sujetos a términos y condiciones adicionales. En ese caso, el uso que el Usuario haga de dichos servicios estará sujeto, además, a los referidos términos y condiciones adicionales, que se incorporan a los presentes Términos y Condiciones por medio de esta referencia. En caso que el Usuario no los acepte, deberá abstenerse de utilizar en cualquier forma dichos servicios adicionales.' },
    { title: 'DEFINICIONES.' },
    { paragraphe: 'Para mejor claridad de lo expresado en el presente instrumento, utilizaremos términos definidos. Para efectos de los presentes Términos y Condiciones, los términos que aparezcan definidos en mayúsculas y que no hayan sido definidos de forma distinta en diversas secciones del presente documento, tendrán el significado que a continuación se les atribuye:' },
    { title: '“Carrito Virtual”' },
    { paragraphe: 'se refiere a la herramienta informática desplegada en los Medios Digitales que permitirá al Usuario identificar el o los Productos que haya preseleccionado para realizar una Transacción, de tiempo en tiempo.' },
    { title: '“Contraprestación”' },
    { paragraphe: 'se refiere al importe, expresado en pesos mexicanos (MXN), que será sufragado por el Usuario y en favor de Nutenta por cada Transacción, mismo que será el resultado de la operación aritmética de sumar los Precios del o de los Productos seleccionados en el Carrito Virtual al momento de que el Usuario elija la opción de pago y posteriormente, adicionar la tarifa de envío.' },
    { title: '“Medio de Pago”' },
    { paragraphe: 'se refiere al dinero en efectivo contra entrega de Productos, la tarjeta de crédito, tarjeta de débito, tarjeta de servicios o cualquier otra modalidad de pago físico o electrónico aceptada en o a través de la Plataforma, misma que será utilizada por los Usuarios para pagar la Contraprestación.' },
    { title: '“Mensaje de Datos”' },
    { paragraphe: 'tendrá el significado establecido en el Artículo 89 del Código de Comercio.' },
    { title: 'Pedido”' },
    { paragraphe: 'se refiere al o a los Productos que hayan sido preparados, empacados y/o embalados para su entrega en el domicilio designado por el Usuario, previa celebración de una Transacción.' },
    { title: '“Precios”' },
    { paragraphe: 'Se refiere a los importes fijados como precios por cada Producto, mismos que serán desplegados en los Medios Digitales, podrán estimarse por importe unitario o por cualquier otro método, y podrán sufrir cambios o modificaciones, de tiempo en tiempo. Salvo que se indique expresamente lo contrario, los precios de los Productos incluirán el Impuesto al Valor Agregado (IVA), cuyo importe será expresamente desglosado en el recibo y en la factura fiscal correspondientes. Los precios no incluyen la tarifa de envío.' },
    { title: '“Productos”' },
    { paragraphe: 'se refiere a los bienes y mercaderías de abarrotes, comercializados través de los Medios Digitales, incluyendo de forma enunciativa pero no limitativa toda clase de alimentos, bebidas, bebidas alcohólicas y/o cualquier otro que sea ofrecido por Nutenta en la Plataforma.' },
    { title: '“Transacción”' },
    { paragraphe: 'se refiere a la operación mercantil de compraventa de uno o más Productos seleccionados en el Carrito Virtual; actuando el Usuario como comprador y Nutenta como vendedora.' },
    { paragraphe: 'Los términos definidos anteriormente podrán ser utilizados a lo largo del presente documento o el Aviso de Privacidad, indistintamente, en singular o en plural; en masculino, en femenino o en neutro; sin que dicha utilización modifique su significado. En caso de que a los términos definidos en la presente sección se les haya atribuido un significado explicativo en otras secciones del presente documento, ambos significados se leerán e interpretarán conjuntamente. Los términos definidos exclusivamente en diversas secciones del presente instrumento tendrán los significados que ahí se les atribuye.' },
    { title: 'ACCESO Y USO DE LOS MEDIOS DIGITALES.' },
    { paragraphe: 'Sólo aquellas personas que proporcionen y consientan el uso de la información requerida en nuestro Aviso de Privacidad para las finalidades primarias y secundarias establecidas en el mismo, estará en posibilidad de crear, usar y mantener su cuenta de usuario en la Plataforma. Se podrá crear una sola cuenta por persona y la persona que crea un Usuario es la única persona autorizada para el acceso a la Plataforma por intermedio de dicho Usuario. Los Usuarios deberán registrarse en la Plataforma, accediendo a la misma por medio de la Aplicación o del Sitio Web o cualesquier otros Medios Digitales disponibles, con el propósito de obtener una cuenta y una contraseña de acceso (“Cuenta de Usuario”) o bien, la propia Nutenta podrá otorgar a los Usuarios que ésta decida su correspondiente Cuenta de Usuario, entregando el usuario y contraseña de acceso preliminar, la cual podrá ser posteriormente cambiada directamente por el Usuario a través de la Plataforma. Los Usuarios podrán crear su Cuenta de Usuario siguiendo los pasos señalados en la propia Plataforma y deberán proporcionar la información personal correspondiente en todos los campos, con datos válidos, precisos y veraces. Los Usuarios están obligados a mantener la antedicha información personal actualizada en todo momento. Nutenta se reserva el derecho de solicitar, en cualquier momento, determinada información o documentación a los Usuarios con el propósito de verificar la veracidad de la información proporcionada, así como de suspender temporalmente las Cuentas de Usuario cuya información no haya podido ser corroborada, o aquéllas cuentas que se estimen han sido creadas con propósitos fraudulentos o con motivo de alguna amenaza de ciberseguridad.' },
    { paragraphe: 'Todos los Usuarios declaran que cuentan con capacidad para contratar, de acuerdo con la legislación aplicable en sus respectivos domicilios. Únicamente podrán solicitar la habilitación de una Cuenta de Usuario las personas que tengan mayoría de edad, es decir, dieciocho (18) años cumplidos al momento de registrarse en la Plataforma. En caso de que una persona menor de edad se registre en la Plataforma, las personas que tengan patria potestad, la tutela o la supervisión del menor serán solidariamente responsables por cualesquier daños y/o perjuicios que puedan ser ocasionados por el menor, así como de las obligaciones que con motivo del uso de los Medios Digitales lleguen a tener con Nutenta.' },
    { paragraphe: 'Los Usuarios serán en todo momento responsables de la custodia de su contraseña, asumiendo en consecuencia, cualesquier daños y perjuicios que pudieran derivarse de su uso indebido, así como de la cesión, revelación o extravío de la misma. Toda Transacción realizada en la Plataforma será considerada como un Mensaje de Datos y se presumirá realizada por el Usuario de la Cuenta de Usuario correspondiente conforme a lo establecido en los Artículos 90, fracción II, y 90 bis del Código de Comercio. Nutenta no tiene control sobre el uso de ninguna Cuenta de Usuario y renuncia expresamente a cualquier responsabilidad derivada de la misma. En caso de olvido de la contraseña o de cualquier otra circunstancia que suponga un riesgo de acceso y/o utilización por parte de terceros no autorizados, el Usuario lo comunicará inmediatamente al Centro de Atención y Soporte (como dicho término se define adelante), a fin de que Nutenta proceda inmediatamente al bloqueo y sustitución de la misma. En todo caso, cualesquier operaciones realizadas antes de dicha comunicación y la confirmación del bloqueo y sustitución de dicha cuenta por parte de Nutenta, sereputarán efectuadas por el Usuario.' },
    { paragraphe: 'Los Usuarios reconocen y aceptan que cualesquiera comunicaciones, incluyendo cualesquier Transacciones, intercambiadas o realizadas a través de los Medios Digitales utilizando su Cuenta de Usuario, serán consideradas como un Mensaje de Datos. Las Transacciones que sean realizadas por los Usuarios a través de la Plataforma, mediante el uso de su respectiva Cuenta de Usuario, se considerará como la manifestación de su consentimiento y aceptación respecto de la Transacción otorgada mediante una firma electrónica, teniendo los efectos legales atribuidos conforme a lo establecido en el Código de Comercio y demás leyes aplicables.' },
    { title: 'TRANSACCIONES.' },
    { paragraphe: 'La celebración de una Transacción se sujetará a las siguientes previsiones:' },
    { paragraphe: 'Transacciones. Los Usuarios podrán utilizar la Plataforma para seleccionar el o los Productos de su interés y colocarlos en un Carrito Virtual, con la especificación del producto elegido y de la cantidad solicitada del mismo. En cualquier momento, el Usuario podrá elegir realizar el pago del o de los Productos que se encuentren seleccionados, de tiempo en tiempo, en el Carrito Virtual. Al momento de seleccionar la opción de pagar o cualquier otra semejante, se reputará realizada una Transacción. Por motivo de la celebración de una Transacción, el Usuario autoriza a Nutenta realizar el cargo de la Contraprestación sobre el Medio de Pago. El Usuario recibirá un recibo por motivo de cada Transacción, mismo que deberá descargar y conservar.' },
    { paragraphe: 'Precios. Los Precios podrán estar sujetos a cambios de momento a momento, quedando bajo la responsabilidad del Usuario completar la Transacción.' },
    { paragraphe: 'Especificaciones de los Productos. Las características y especificaciones de los Productos pueden cambiar sin previo aviso. Las fotografías corresponden a un producto similar representado únicamente de manera ilustrativa.' },
    { paragraphe: 'Cargos temporales. El Usuario autoriza a Nutenta para realizar un cargo temporal con el objetivo de validar la idoneidad del Medio de Pago. Todo cargo temporal será reembolsado una vez verificado lo anterior.' },
    { paragraphe: 'Disponibilidad. Todos los Productos que se ofrecen en la Plataforma se encuentran sujetos a disponibilidad. En ciertos casos, habrá Productos que reporten una disponibilidad inmediata y otros que tengan uno o más días de espera para encontrarse sujetos a disposición del Usuario. Tratándose de Pedidos que reporten Productos con disponibilidad inmediata y otros que no reporten dicha disponibilidad por razón de tiempo o por motivo de la dirección de envío específica, Nutenta podrá sugerir al Usuario la división del Pedido para su entrega parcial en dos fechas distintas o la modificación de la dirección de envío o la cancelación de los Productos no disponibles. La mercancía está sujeta a existencias, por lo que el tiempo de entrega puede variar previo aviso por parte de Nutenta, o incluso se podrá proceder con la cancelación de la orden y la devolución del pago en caso de no ser un Producto resurtible.' },
    { paragraphe: 'Productos no disponibles. Es posible que ciertos Productos no se encuentren disponibles una vez que el Usuario haya realizado la Transacción. En ese caso, el Usuario tendrá las siguientes opciones: (i) solicitar la sustitución del o de los Productos cuya disponibilidad se haya agotado, a través de un cupón electrónico que ampare el valor de los Productos no disponibles; (ii) pedir la devolución del importe de los Productos no disponibles con abono al Medio de Pago; o (iii) esperar a que dichos Productos vuelvan a tener disponibilidad, en cuyo caso se le enviarán de inmediato.' },
    { paragraphe: 'Bebidas alcohólicas. Toda Transacción que incluya bebidas alcohólicas y/o cajetillas solo podrá ser requerida por Usuarios mayores de 18 años de edad. El repartidor asociado a Nutenta tendrá la facultad de cerciorarse de que la persona que reciba el Pedido sea mayor de edad, por medio de la solicitud de un medio de identificación oficial. De lo contrario, no se podrá realizar la entrega del Pedido, liberando de toda responsabilidad, tanto a Nutenta, sus directores, empleados, subsidiarias, afiliados, agentes y representantes, como también al repartidor, por no proceder a la entrega por la falta de acreditación de identidad del Usuario.' },
    { paragraphe: 'Compra mínima. Nutenta se reserva el derecho de establecer un importe de compra mínima por cada Transacción. Con el propósito de resguardar la seguridad de nuestros repartidores asociados, Nutenta podrá establecer límites de peso o de cantidad por Producto o por Pedido general, para cada Transacción. En ese caso, el Usuario podrá realizar una o más Transacciones adicionales para satisfacer sus necesidades de forma íntegra.' },
    { title: 'ENTREGA.' },
    { paragraphe: 'La entrega de los Productos quedará sujeta a las siguientes disposiciones. Los Usuarios podrán consultar el estado del o de los Pedido(s) que tengan en curso, en la opción habilitada para tal efecto en los Medios Digitales.' },
    { paragraphe: 'Repartidores asociados. Nutenta tendrá la libertad de contratar o subcontratar con terceras personas, bajo cualquier título legal aplicable, para efectos de encomendarles la entrega de los Pedidos, sin que ello exima a Nutenta de responder por la entrega íntegra del Pedido.' },
    { paragraphe: 'Domicilio de entrega. Al momento de celebrar una Transacción, el Usuario podrá señalar un domicilio para que tenga verificativo la entrega del Pedido. A falta de designación expresa, se reputará como domicilio de entrega aquél que el Usuario haya señalado al momento de registrarse en la Plataforma.' },
    { paragraphe: 'Horario de entrega. La entrega de los Pedidos se realizará el día siguiente a aquel en el que el Usuario haya realizado el Pedido correspondiente, lo anterior siempre y cuando dicho Pedido se realice antes de las 23:55 horas, hora del centro de México y en el entendido de que no se computarán para estos efectos los domingos ni los días de descanso obligatorios en términos de lo establecido en el artículo 74 de la Ley Federal del Trabajo.' },
    { paragraphe: 'Entrega y tiempo de tolerancia. Una vez que llegue el repartidor asociado en el horario de entrega, como primer punto de contacto con el Usuario tocará el timbre o en su caso, solicitará asistencia con el personal de seguridad y vigilancia. En caso de que no se encuentre el Usuario o alguna persona autorizada para recibir el Pedido, el repartidor asociado podrá comunicarse por vía telefónica para intentar localizarlo. Sin excepción alguna, el tiempo máximo de tolerancia para esperar a una persona que reciba el Pedido será de cinco (5) minutos.' },
    { paragraphe: 'Pedido incompleto. En el evento de que un Pedido se encuentre incompleto por haberse enviado menos Productos de los solicitados por el Usuario, o algún Producto en menor cantidad de la requerida, el Usuario deberá informar a Nutenta de tal situación a través del Centro de Atención y Soporte. En todo caso, no se cobrará por el faltante, por lo que Nutenta, a elección del Usuario, realizará el abono correspondiente al Medio de Pago a manera de reembolso o bien, otorgará al Usuario un cupón de descuento equivalente al faltante reportado, para ser utilizado en la Plataforma.' },
    { title: 'DEVOLUCIONES Y CANCELACIONES.' },
    { paragraphe: 'Cancelación: Si el Usuario desea cancelar un Pedido, podrá hacerlo el mismo día en que haya realizado dicho Pedido siempre y cuando la cancelación se realice antes de las 20:00 horas, hora del centro de México. La cancelación del Pedido podrá solicitarse a través de la sección de “Mis Pedidos” en la Aplicación. Si el Pedido se realiza después de las 20:00 horas, hora del centro de México, no habrá cancelaciones.' },
    { paragraphe: 'Devolución: Las devoluciones por Productos defectuosos o dañados deberán ser notificadas a Nutenta dentro de las veinticuatro (24) horas posteriores a que el Usuario haya recibido su Pedido. No se aceptarán devoluciones con posterioridad al plazo antes indicado. Lo anterior en el entendido de que Nutenta se reserva el derecho de revisar los Productos devueltos por los Usuarios para asegurarse de que el defecto o daño notificado no se haya presentado, ocurrido o realizado conposterioridad a la entrega del Producto y sea imputable a los Usuarios.' },
    { paragraphe: 'El Usuario deberá ponerse en contacto a través de nuestro Centro de Atención y Soporte al teléfono de atención al cliente (+52 55 2723 6355). Nuestros representantes informarán al Usuario el procedimiento a seguir para la devolución del producto y completar el procedimiento para el reembolso respectivo en créditos o en al Medio de Pago usado en el Pedido.' },
    { title: 'PROMOCIONES.' },
    { paragraphe: 'Nutenta podrá difundir a través de cualesquier medios publicitarios descuentos a los Usuarios, los cuales tendrán una vigencia máxima de uso hasta por 7 (siete) días naturales desde el día en que hayan sido promocionadas al público en general, salvo que en el texto de la promoción se indique expresamente lo contrario.' },
    { paragraphe: 'Nutenta no aplica los descuentos y promociones respecto de los Productos disponibles en la Plataforma que se muestran en otras tiendas, comercios, fábricas o centros de abasto. Los precios que cobramos son los que publicamos, aunque es posible que, de vez en cuando, existan promociones con diferentes marcas.' },
    { title: 'PLAN DE RECOMPENSAS' },
    { paragraphe: 'Nutenta se reserva el derecho de entregar puntos a los Usuarios como parte de campañas de marketing para impulsar el uso de la Plataforma, compras, o la recomendación a otros nuevos usuarios, entre otras razones (“Puntos Nutenta”).' },
    { paragraphe: 'Los Puntos Nutenta tienen como objetivo ser utilizados en forma de adquisición de productos del catálogo ofrecido por Nutenta en la Plataforma. El catálogo podrá ser modificado de tiempo en tiempo por Nutenta sin necesidad de notificación previa al Usuario.' },
    { paragraphe: 'En ningún caso los Puntos Nutenta pueden ser transferidos de una Cuenta de Usuario a otra ni ser canjeados por dinero en efectivo. Los Puntos Nutenta no pueden ser obtenidos mediante la creación de múltiples Cuentas de Usuario. Por lo tanto, Nutenta se reserva el derecho de establecer qué productos permitirán la obtención de Puntos Nutenta, así como los montos en pesos mexicanos (MXN) que deberán gastar los Usuarios a través de su Cuenta de Usuario, para obtener los Puntos Nutenta que correspondan a dichos montos, lo anterior salvo que Nutenta establezca alguna condición, incentivo, dinámica o promoción específica para el otorgamiento de los Puntos Nutenta. Los Puntos Nutenta acumulados en varias Cuentas de Usuario no pueden combinarse en una sola Cuenta de Usuario.' },
    { paragraphe: 'Nutenta podrá establecer de tiempo y tiempo y a su plena discreción formas distintas de adquisición de Puntos Nutenta las cuales estarán visibles para el usuario en los Medios Digitales.' },
    { paragraphe: 'Los Puntos Nutenta pueden tener una duración limitada de tiempo y Nutenta se reserva el derecho de revocarlos sin necesariamente notificar a los Usuarios de ello. Nutenta podrá suspender o dar por terminada una cuenta de Puntos Nutenta, o la capacidad de un Usuario para participar en de la acumulación de éstos, o de cualquier campaña de marketing, en cualquier momento y por cualquier razón. RequisitosLos requisitos e incentivos también pueden cambiar en cualquier momento a discreción de Nutenta sin necesidad de notificación previa al Usuario.' },
    { paragraphe: 'Puntos Nutenta obtenidos como resultado de actividades fraudulentas son nulos y sin efecto. Nos reservamos el derecho de suspender las Cuentas de Usuario o eliminar recomendaciones si nos damos cuenta de cualquier actividad que creemos es abusiva o fraudulenta.' },
    { title: 'USO DE LA PLATAFORMA' },
    { paragraphe: 'El uso de la Plataforma es bajo el propio riesgo del Usuario. Los Servicios se prestan tal como son ofrecidos, sin garantías de ningún tipo, explícita o implícita, incluyendo, pero no limitada a, las garantías de comercialización, idoneidad del Producto para un propósito particular y no infracción.' },
    { paragraphe: 'NUTENTA NO EFECTÚA NINGUNA CLASE DE DECLARACIÓN O GARANTÍA RELATIVA A LA EXACTITUD O TOTALIDAD DEL CONTENIDO O PRODUCTOS OFRECIDOS A TRAVÉS DEL USO DE LA PLATAFORMA O SOBRE EL CONTENIDO DE CUALQUIER APLICACIÓN, SITIO WEB O CUALQUIER OTRO MEDIO DIGITAL VINCULADO AL USO DE LA PLATAFORMA. NUTENTA NO ASUME NINGUNA RESPONSABILIDAD DERIVADA DE (I) ERRORES O IMPRECISIONES DEL CONTENIDO O LOS PRODUCTOS; (II) LESIONES CORPORALES O DAÑOS A LA PROPIEDAD, DE CUALQUIER NATURALEZA, COMO RESULTADO DE SU ACCESO Y USO DE LA PLATAFORMA; O (III) ACCESO NO AUTORIZADO O USO DE SERVIDORES SEGUROS DE NUTENTA Y/O CUALQUIER INFORMACIÓN PERSONAL Y/O FINANCIERA ALMACENADA EN ELLOS.' },
    { paragraphe: 'Nutenta no garantiza que la Plataforma funcionará libre de errores o que esté libre de virus, malware u otros programas maliciosos. Nutenta hará sus mejores esfuerzos por mantener el buen y correcto funcionamiento de los Medios Digitales, así como para mitigar la presencia de virus y/o de otros elementos introducidos a los Medios Digitales por terceros ajenos, además adoptará diversas medidas de protección para proteger los Medios Digitales contra ataques informáticos y cibernéticos de terceros. Sin embargo, los Usuarios reconocen que los Medios Digitales podrán no estar disponibles debido a dificultades técnicas, fallas en el internet, afectaciones en las redes de telecomunicaciones, o por cualquier circunstancia ajena a Nutenta.' },
    { paragraphe: 'NUTENTA EN LA MEDIDA MÁXIMA PERMITIDA POR LA LEY, RENUNCIA A TODA GARANTÍA, EXPLÍCITA O IMPLÍCITA, INCLUYENDO SIN LIMITACIÓN LAS GARANTÍAS DE COMERCIALIZACIÓN, NO VIOLACIÓN DE DERECHOS DE TERCEROS Y LA GARANTÍA DE IDONEIDAD PARA UN PROPÓSITO PARTICULAR. NUTENTA NO GARANTIZA, BAJO NINGUNA CIRCUNSTANCIA, LA EXACTITUD, CONFIABILIDAD, EXHAUSTIVIDAD Y ACTUALIDAD DE LOS CONTENIDOS, SERVICIOS, SOPORTE, SOFTWARE, TEXTOS, GRÁFICOS O VÍNCULOS. NUTENTA Y SUS FILIALES Y PROVEEDORES DE LICENCIAS NO GARANTIZAN, BAJO NINGUNA CIRCUNSTANCIA, QUE LA INFORMACIÓN PERSONAL SUMINISTRADA POR EL USUARIO PUEDA SER OBJETO DE APROPIACIÓN INDEBIDA, INTERCEPTADA, BORRADA, DESTRUIDA O USADA POR TERCEROS.' },
    { title: 'LIMITACIÓN DE RESPONSABILIDAD' },
    { paragraphe: 'El Usuario acepta que Nutenta no se hace responsable por ningún daño directo, indirecto, lucro cesante, daño emergente, daño incidental, especial o consecuencial, o perjuicio proveniente de o en relación con (i) el uso de la Plataforma y/o la Aplicación; (ii) la responsabilidad de cualquier Usuario o repartidor que no preste sus servicios bajo subordinación y dependencia de Nutenta; (iii) el rendimiento o navegación en la Plataforma o sus enlaces a otros sitios web, incluso si Nutenta ha sido informado de la posibilidad de tales daños; (iv) la calidad y cantidad de los Productos entregados al Usuario; o (v) la seguridad del uso de los Productos adquiridos.' },
    { paragraphe: 'Además, el Usuario acepta que Nutenta no se hace responsable de los daños derivados de la interrupción, suspensión o terminación de los Servicios, incluyendo sin limitación daño directo, indirecto, lucro cesante, daño emergente, daño incidental, especial o consecuencial o perjuicio, aun cuando dicha interrupción, suspensión o terminación estuviera o no justificada. En ningún caso la responsabilidad total de Nutenta ante el Usuario por cualquier clase de pérdidas podrá exceder los montos pagados por éste a Nutenta.' },
    { title: 'INDEMNIZACIÓN' },
    { paragraphe: 'El Usuario se obliga a defender, indemnizar y mantener a salvo a Nutenta, sus funcionarios, directores, empleados, agentes y afiliados, de y contra cualquier pérdida, reclamos, acciones, costos, daños, sanciones, multas y gastos, incluyendo sin limitación honorarios de abogados, que surjan de, relacionados con o resultantes del uso no autorizado de la Plataforma por parte del Usuario, o de cualquier incumplimiento de estos Términos y Condiciones, incluyendo sin limitación, cualquier violación de cualquier ley, disposición general orden administrativa, norma o reglamento. Nutenta dará aviso, a la brevedad, de cualquier reclamación, demanda o procedimiento, y tendrá derecho a asumir la defensa respecto de cualquier reclamación, demanda o procedimiento.' },
    { title: 'CASO FORTUITO Y DE FUERZA MAYOR' },
    { paragraphe: 'Nutenta no será responsable frente a los Usuarios, conforme al presente instrumento, en caso de que no puedan utilizarse la Plataforma, la Aplicación y/o los Medios Digitales o no se puedan celebrar Transacciones debido a caso fortuito o causas de fuerza mayor, incluyendo, pero sin limitar, incendios, inundaciones, huracanes, tormentas, ciclones, terremotos, sismos, movimientos telúricos, huelgas, guerras, insurrecciones, motines, rebeliones, epidemias, pandemias, clausuras, ataques cibernéticos, la revocación general o limitación al público usuario en el uso del software o lenguaje de programación necesario para operar la Plataforma o la Aplicación, casos fortuitos u otras causas de naturaleza similar o distinta, y cualesquiera otras causas sobre las que Nutenta no tenga control.' },
    { title: 'CENTRO DE ATENCIÓN Y SOPORTE.' },
    { paragraphe: 'Para realizar cualesquier solicitudes, quejas o reportes relacionados con los Servicios, así como para solicitar cualesquier aclaraciones relacionadas con las Transacciones, los Usuarios deberán comunicarse al centro de atención y soporte de Nutenta (“Centro de Atención y Soporte”), dentro del plazo máximo de 1 día natural posterior al acontecimiento que deseen reportar o cuya aclaración soliciten (“Aclaraciones”). Centro de Atención y Soporte Teléfono: +52-55-2723-6355. Nutenta contará con un plazo de 7 (siete) días naturales para resolver las Aclaraciones correspondientes.' },
    { paragraphe: 'Toda referencia contenida en el presente instrumento relativa a comunicaciones que el Usuario deberá efectuar para con Nutenta, deberán realizarse al Centro de Atención.' },
    { title: 'PRIVACIDAD.' },
    { paragraphe: 'Al suscribir o aceptar los presentes Términos y Condiciones, los Usuarios declaran que han leído y han aceptado expresamente el Aviso de Privacidad de Nutenta, que se encuentra a su disposición en la sección de “Mi Perfil” de la Aplicación. Para más información sobre el tratamiento de sus datos personales, los Usuarios deberán consultar el Aviso de Privacidad.' },
    { paragraphe: 'Los Usuarios se comprometen a realizar las Transacciones desde un dispositivo seguro, asumiendo total y absoluta responsabilidad por la pérdida, daño, sustracción u olvido de cualquier información (incluyendo su Cuenta de Usuario y demás credenciales de acceso) y por cualquier hecho que pudiere afectar la confidencialidad en el uso y acceso a la Plataforma. Las Transacciones, accesos, compras y/o consultas realizadas con las credenciales de acceso del Usuario en la Plataforma, se considerarán válidas y se entenderán que han sido realizadas directamente por el Usuario.' },
    { title: 'FACTURACIÓN.' },
    { paragraphe: 'Los Usuarios podrán solicitar a Nutenta Comprobantes Fiscales Digitales (CFDIs) por cada Transacción. Para tal efecto, deberán solicitar el CFDI correspondiente a través de los Medios Digitales y enviar los requisitos necesarios y correctos para la emisión de la factura correspondiente, dentro del mismo mes en el que se haya realizada la Transacción correspondiente.' },
    { title: 'DERECHOS DE PROPIEDAD INTELECTUAL E INDUSTRIAL.' },
    { paragraphe: 'Los Usuarios reconocen y aceptan que todos los derechos de propiedad intelectual e industrial sobre la Plataforma y sobre todos los contenidos, materiales y demás elementos insertos en los Medios Digitales (la “Propiedad Intelectual”) pertenecen a Nutenta o a los proveedores de Nutenta. Se encuentra estrictamente prohibida cualquier reproducción total o parcial, distribución, transmisión, copia, alteración, explotación, publicación, difusión o disposición de la Propiedad Intelectual, sin el consentimiento previo y por escrito de Nutenta o de los terceros a los que pertenezca la Propiedad Intelectual, según corresponda, reservándose el ejercicio de todas las acciones tanto civiles como penales destinadas al resguardo de sus legítimos derechos de propiedad intelectual e industrial. Por lo tanto, los Usuarios reconocen que únicamente podrán utilizar la Propiedad Intelectual que se encuentra en la Plataforma, la Aplicación y/o en los Medios Digitales para fines personales de consumo, incluyendo para la revisión, compra y consulta de los productos o servicios ofrecidos a través de dicha Plataforma, Aplicación y Medios Digitales. Nutenta no otorga ninguna garantía, explícita o implícita, respecto de la licitud, validez o no infracción de derechos de la Propiedad Intelectual que se utilice o reproduzca en la Plataforma, la Aplicación o los Medios Digitales.' },
    { title: 'RELACIÓN ENTRE LAS PARTES.' },
    { paragraphe: 'Las partes que reconocen que son independientes entre sí. La aceptación de estos Términos y Condiciones únicamente crea una relación de carácter estrictamente mercantil entre dichas partes, sin que pueda interpretarse como que crea una relación entre ellas de agencia, asociación, empresa conjunta, empleado-empleador o franquiciador-franquiciado.' },
    { title: 'CESIÓN.' },
    { paragraphe: 'Los Usuarios no podrán ceder sus derechos y obligaciones asumidos al suscribir los presentes Términos y Condiciones, sin el consentimiento previo y por escrito de Nutenta.' },
    { paragraphe: 'Nutenta podrá ceder, transferir o delegar cualquiera de sus derechos y obligaciones en virtud de estos Términos y Condiciones sin el consentimiento del Usuario.' },
    { title: 'NOTIFICACIONES.' },
    { paragraphe: 'El Usuario acepta recibir comunicaciones o notificaciones por parte de Nutenta por cualquier tipo de Mensaje de Datos, incluyendo correos electrónicos, mensajes de texto, vía WhatsApp y notificaciones a través de la Plataforma, la Aplicación y/o los Medios Digitales o a través de la dirección de correo electrónico facilitada por el Usuario al registrar su Cuenta de Usuario. Todos los avisos, comunicaciones o modificaciones serán considerados debidamente entregados desde el momento de su publicación o intercambio en la Plataforma, la Aplicación y/o los Medios Digitales, o bien desde el momento en que sea notificado al Usuario, según corresponda en términos del presente párrafo. El Usuario podrá habilitar y/o deshabilitar las notificaciones que recibe en la Plataforma.' },
    { paragraphe: 'El Usuario acepta que todos los contratos, avisos, mensajes y otras notificaciones y comunicaciones que sean enviados por Nutenta por medios electrónicos satisfacen cualquier requisito legal de forma escrita y cuentan con plenos efectos legales y de validez.' },
    { title: 'MODIFICACIONES.' },
    { paragraphe: 'Los presentLos presentes Términos y Condiciones podrán ser modificados, adicionados o reformados, de tiempo en tiempo, a la entera y absoluta discreción de Nutenta, sin necesidad de previo aviso, bastando la simple actualización de la fecha de última modificación del presente instrumento. Sin embargo, tales cambios sólo se aplicarán desde el momento en que sean publicados en la Plataforma, la Aplicación y/o los Medios Digitales y regirán para las Transacciones que se celebren con posterioridad a su entrada en vigor, sin alterar las transacciones celebradas con anterioridad.es Términos y Condiciones podrán ser modificados, adicionados o reformados, a la entera y absoluta discreción de Nutenta, sin necesidad de previo aviso, bastando la simple actualización de la fecha de última modificación del presente instrumento. Sin embargo, tales cambios sólo se aplicarán desde el momento en que sean publicados en la Plataforma, la Aplicación y/o los Medios Digitales y regirán para las Transacciones que se celebren con posterioridad a su entrada en vigor, sin alterar las transacciones celebradas con anterioridad.' },
    { paragraphe: 'En el evento de que el Usuario no esté de acuerdo con las modificaciones realizadas a los presentes éste podrá solicitar a Nutenta su baja de la Plataforma y/o Aplicación dentro de los treinta (30) días naturales posteriores al aviso, sin responsabilidad alguna a su cargo. Se entenderá que el Usuario acepta las modificaciones efectuadas a los presentes Términos y Condiciones si éste solicita o participa en cualquier Transacción en fecha posterior a que tales modificaciones entren en vigor, manteniendo vigente su derecho a dar por terminado el presente instrumento en términos de lo dispuesto en el presente párrafo.En el evento de que el Usuario no esté de acuerdo con las modificaciones realizadas a los presentes éste podrá solicitar a Nutenta la terminación del mismo dentro de los treinta (30) días naturales posteriores al aviso, sin responsabilidad alguna a su cargo. Se entenderá que el Usuario acepta las modificaciones efectuadas a los presentes Términos y Condiciones si éste solicita o participa en cualquier Transacción en fecha posterior a que tales modificaciones entren en vigor, manteniendo vigente su derecho a dar por terminado el presente instrumento en términos de lo dispuesto en el presente párrafo.' },
    { title: 'VIGENCIA' },
    { paragraphe: 'Los presentes Términos y Condiciones serán vigentes, obligatorios y vinculantes para todos los Usuarios que tengan una Cuenta de Usuario habilitada en la Plataforma y no soliciten su baja o cancelación. En caso de que algún Usuario solicite la baja o la cancelación de su Cuenta de Usuario, quedará relevado de cumplir con lo previsto en el presente documento, pero permanecerán vigentes todas aquellas obligaciones relacionadas con los daños, perjuicios o responsabilidades (de carácter civil, penal, administrativa o de cualquier otra índole) en que haya incurrido, en su caso, el Usuario en contra de otros Usuarios, de Nutenta o de cualquier tercero.' },
    { title: 'LEGISLACIÓN APLICABLE Y JURISDICCIÓN COMPETENTE.' },
    { paragraphe: 'Nutenta y los Usuario en este acto convienen de manera incondicional e irrevocable que los presentes Términos y Condiciones serán regidos e interpretados de acuerdo con la legislación mercantil y supletoriamente con la legislación civil federal vigentes de los Estados Unidos Mexicanos, así como de conformidad con la regulación aplicable en materia de protección al consumidor, en lo conducente. Asimismo, cualquier controversia derivada de estos Términos y Condiciones, su existencia, validez, interpretación, alcance o cumplimiento, será sometida a los Tribunales de la Ciudad de México competentes para su conocimiento, y en este acto expresa e incondicionalmente renuncian, en los términos más amplios permitidos por la ley, a cualquier otro fuero que pudiera corresponderles por razón de sus domicilios actuales o futuros o por cualquier otra razón.' },
  ];

  return (
    <View style={{ backgroundColor: backgroundColor }}>

      <ScrollView>
        <View style={styles.container}>
          {
              terms.map((t, id) => {
                return t.title ? (
                  <Text key={`title-${id}`} style={[styles.title, styleTitle]}>{t.title}</Text>
                ) : t.paragraphe ? (
                  <Text key={`paragraphe-${id}`} style={[styles.paragraphe, styleParagraphe]}>{t.paragraphe}</Text>
                ) : null;
              })
          }
        </View>
      </ScrollView>
    </View>
  )
}

export default TermsConditionsComponent;

const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    width: responsiveScreenWidth(100),
    paddingHorizontal: 20,
    paddingBottom: responsiveScreenHeight(30)
  },
  title: {
    fontFamily: Roboto.Bold,
    color: color.darkGray,
    paddingTop: 20,
  },
  paragraphe: {
    marginVertical: 15,
    fontFamily: Roboto.Regular,
    color: color.darkGray,
  }
});